### ISSUE TITLE
problem with the Dapp-angular-starter package

### ISSUE THREAD

**Issue by rfikki** [SylTi/eth-dapp-angular-truffle-starter#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Rocky\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'installAll' ]
2 info using npm@4.2.0
3 info using node@v7.4.0
4 verbose run-script [ 'preinstallAll', 'installAll', 'postinstallAll' ]
5 info lifecycle Dapp-angular-starter@0.0.1~preinstallAll: Dapp-angular-starter@0.0.1
6 silly lifecycle Dapp-angular-starter@0.0.1~preinstallAll: no script for preinstallAll, continuing
7 info lifecycle Dapp-angular-starter@0.0.1~installAll: Dapp-angular-starter@0.0.1
8 verbose lifecycle Dapp-angular-starter@0.0.1~installAll: unsafe-perm in lifecycle true
9 verbose lifecycle Dapp-angular-starter@0.0.1~installAll: PATH: C:\Users\Rocky\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\projects\erc20-angular\node_modules\.bin;C:\Users\Rocky\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Rocky\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Python27\python.exe;C:\Python27\Lib\site-packages;C:\Python27\Scripts;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\WINDOWS\System32;C:\projects\ethereum-swarm\gopath;C:\Program Files (x86)\QuickTime\QTSystem;C:\Program Files\Git\cmd;C:\Program Files\Rust stable GNU 1.13\bin;C:\Program Files\nodejs;C:\Python27;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Yarn\bin;C:\Go\bin;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared;C:\Program Files (x86)\Common Files\Roxio Shared\VHStoDVD\DLLShared;C:\Users\Rocky\.cargo\bin;C:\Users\Rocky\AppData\Local\.meteor;C:\Program Files (x86)\Microsoft VS Code\bin;C:\projects\go-ipfs;C:\projects\ethereum-swarm\gopath;C:\Users\Rocky\AppData\Local\Microsoft\WindowsApps;C:\Users\Rocky\AppData\Local\atom\bin;C:\Users\Rocky\AppData\Roaming\npm;C:\Python27;C:\Users\Rocky\AppData\Local\Yarn\.bin;C:\Users\Rocky\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle Dapp-angular-starter@0.0.1~installAll: CWD: C:\projects\erc20-angular
11 silly lifecycle Dapp-angular-starter@0.0.1~installAll: Args: [ '/d /s /c', 'npm install && truffle install' ]
12 silly lifecycle Dapp-angular-starter@0.0.1~installAll: Returned: code: 1  signal: null
13 info lifecycle Dapp-angular-starter@0.0.1~installAll: Failed to exec installAll script
14 verbose stack Error: Dapp-angular-starter@0.0.1 installAll: `npm install && truffle install`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Rocky\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Rocky\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Dapp-angular-starter@0.0.1
16 verbose cwd C:\projects\erc20-angular
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rocky\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "installAll"
19 error node v7.4.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error Dapp-angular-starter@0.0.1 installAll: `npm install && truffle install`
23 error Exit status 1
24 error Failed at the Dapp-angular-starter@0.0.1 installAll script 'npm install && truffle install'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the Dapp-angular-starter package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm install && truffle install
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs Dapp-angular-starter
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls Dapp-angular-starter
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by SylTi** [comment]
can you run manually `npm install` and then `truffle install` to see what is failing?
if it fail on npm install because of the zeppelin-solidity package, you need to run `npm install zeppelin-solidity --ignore-scripts` they have a .sh script that fail on windows. It should be removed in their next release. https://github.com/OpenZeppelin/zeppelin-solidity/issues/253

**Comment by SylTi** [comment]
fixed in https://github.com/SylTi/eth-dapp-angular-truffle-starter/commit/b80bfd8f08f5b717fa94a360b3ce7515c985b301
